te table stock_market_a (
	STOCK_ID VARCHAR(6) NOT NULL,
	STOCK_NM VARCHAR(15),
	STK_PRC_RT VARCHAR(10),
	CHNG_PCNT VARCHAR(10),
	CHNG_AMOUNT VARCHAR(10),
	CHNG_PCNT_5MIN varchar(10),
	TRADE_VOLUME VARCHAR(20),
	STK_TURNOVER_W VARCHAR(20),
	STK_TURNOVER_RATIO VARCHAR(10),
	STK_AMPLITUDE VARCHAR(10),
	QUANTITY_RLTV_RATIO VARCHAR(10),
	STK_COMMITTEE_RATIO VARCHAR(10),
	PRC_EARN_RATIO VARCHAR(15),
	DATA_TIME VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table stock_market_b (
	STOCK_ID VARCHAR(6) NOT NULL,
	STOCK_NM VARCHAR(15),
	STK_PRC_RT VARCHAR(10),
	CHNG_PCNT VARCHAR(10),
	CHNG_AMOUNT VARCHAR(10),
	CHNG_PCNT_5MIN varchar(10),
	TRADE_VOLUME VARCHAR(20),
	STK_TURNOVER_W VARCHAR(20),
	STK_TURNOVER_RATIO VARCHAR(10),
	STK_AMPLITUDE VARCHAR(10),
	QUANTITY_RLTV_RATIO VARCHAR(10),
	STK_COMMITTEE_RATIO VARCHAR(10),
	PRC_EARN_RATIO VARCHAR(15),
	DATA_TIME VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table stock_market_small (
	STOCK_ID VARCHAR(6) NOT NULL,
	STOCK_NM VARCHAR(15),
	STK_PRC_RT VARCHAR(10),
	CHNG_PCNT VARCHAR(10),
	CHNG_AMOUNT VARCHAR(10),
	CHNG_PCNT_5MIN varchar(10),
	TRADE_VOLUME VARCHAR(20),
	STK_TURNOVER_W VARCHAR(20),
	STK_TURNOVER_RATIO VARCHAR(10),
	STK_AMPLITUDE VARCHAR(10),
	QUANTITY_RLTV_RATIO VARCHAR(10),
	PRC_EARN_RATIO VARCHAR(15),
	DATA_TIME VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

create table stock_market_gem (
	STOCK_ID VARCHAR(6) NOT NULL,
	STOCK_NM VARCHAR(15),
	STK_PRC_RT VARCHAR(10),
	CHNG_PCNT VARCHAR(10),
	CHNG_AMOUNT VARCHAR(10),
	CHNG_PCNT_5MIN varchar(10),
	TRADE_VOLUME VARCHAR(20),
	STK_TURNOVER_W VARCHAR(20),
	STK_TURNOVER_RATIO VARCHAR(10),
	STK_AMPLITUDE VARCHAR(10),
	QUANTITY_RLTV_RATIO VARCHAR(10),
	PRC_EARN_RATIO VARCHAR(15),
	DATA_TIME VARCHAR(20)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

